// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGwRScEm4Ja63WRkQ7w9NuzD4MIJ14tjw',
    appId: '1:474972096952:web:791266f42f40e1aa44674d',
    messagingSenderId: '474972096952',
    projectId: 'bs-lab-app',
    authDomain: 'bs-lab-app.firebaseapp.com',
    storageBucket: 'bs-lab-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXtf2TYAGtLbp0Gl3yMrrWPO1te_oHQYk',
    appId: '1:474972096952:android:4ef84537ffc88f3d44674d',
    messagingSenderId: '474972096952',
    projectId: 'bs-lab-app',
    storageBucket: 'bs-lab-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpfc-dsmkaf0x-q_KhxozkJbu1agxpMOw',
    appId: '1:474972096952:ios:20dcdb1fa9a8f38944674d',
    messagingSenderId: '474972096952',
    projectId: 'bs-lab-app',
    storageBucket: 'bs-lab-app.firebasestorage.app',
    iosBundleId: 'com.example.bsLabApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpfc-dsmkaf0x-q_KhxozkJbu1agxpMOw',
    appId: '1:474972096952:ios:20dcdb1fa9a8f38944674d',
    messagingSenderId: '474972096952',
    projectId: 'bs-lab-app',
    storageBucket: 'bs-lab-app.firebasestorage.app',
    iosBundleId: 'com.example.bsLabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGwRScEm4Ja63WRkQ7w9NuzD4MIJ14tjw',
    appId: '1:474972096952:web:e3b9558fe0c8c97c44674d',
    messagingSenderId: '474972096952',
    projectId: 'bs-lab-app',
    authDomain: 'bs-lab-app.firebaseapp.com',
    storageBucket: 'bs-lab-app.firebasestorage.app',
  );
}
